services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
        RABBITMQ_DEFAULT_USER: safe
        RABBITMQ_DEFAULT_PASS: safe
  app:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: ecommerce-admin-app
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - maven-cache:/root/.m2
    command: mvn spring-boot:run
    environment:
      SPRING_PROFILES_ACTIVE: manual
    ports:
      - "8080:8080"

volumes:
  maven-cache:
